local t_str = {
	HANDLE_SUCCESS={value="操作成功"},
	PARAM_ERROR={value="参数错误"},
	INVALID_SERVER={value="无法连接服务器"},
	SERVER_ERROR={value="服务器错误"},
	AUTH_FAIL={value="认证失败"},
	INVALID_AUTH_SERVER={value="无法连接认证服务器"},
	USER_CREATE_FAIL={value="用户创建失败"},
	LOGIN_USERNAME={value="用户名"},
	LOGIN_PASS={value="密码"},
	FUNCTION_NOT_OPEN={value="功能未开放"},
	EQUIP_QUALITY={value="NULL|平凡|难得|稀有|珍贵|神器"},
	EQUIP_TYPE={value="武器|盾牌|铠甲|宝具"},
	SKILL_TYPE={value="普攻技|怒气技|三星技|五星技|七星技"},
	PLAYER_CANNOT_DOWN={value="骚年，主角不能下阵哟！"},
	UPDATE_ERR_NONEW={value="没有新版本！"},
	UPDATE_ERR_UNCOMPRESS={value="文件解压错误，更新失败！"},
	UPDATE_ERR_FILE={value="文件错误，更新失败！"},
	UPDATE_ERR_NETWORK={value="网络错误，更新失败！"},
	NEED_UPDATE_SIZE={value="游戏需要更新%d个资源包，总共大小%.2f M，点击确定更新。"},
	UPDATE_CHECKING={value="正在检查更新…"},
	UPDATE_SUCESS={value="游戏更新成功！"},
	UPDATE_DOWNLOADING={value="游戏更新中…"},
	FIGHT_NUM_LESS={value="挑战次数不足，是否购买次数？"},
	RANK_CHANGED={value="该玩家名次已经变更，请重新选择"},
	GREETING_TOO_LONG={value="宣言字数过长"},
	COPY_NOT_REACH={value="前置条件未达成"},
	DIAMEN_NOT_ENOUGH={value="钻石不足"},
	INPUT_CHAT_CONTENT={value="请输入聊天内容！"},
	CHAT_TOO_LONG={value="你的话太长了，请少于30个字！"},
	CHAT_FIRE_WORD={value="含有非法字符："},
	CHAT_REINPUT_WORD={value="请重新输入！"},
	COPY_PASS_NORMAL={value="请先通关普通模式！"},
	DAILY_REACH_MAX={value="已达到每日上限"},
	RECHARGE_DIAMOND={value="你是否要花费%d人民币购买%s？"},
	CHANGE_PLAYER_NAME={value="你是否要花费%d砖石更改昵称？"},
	SHOP_COMMON={value="将消耗%d砖石，确认购买？"},
	SHOP_SCORE={value="将消耗%d积分，确认兑换？"},
	SHOP_BADGE={value="将消耗%d徽章，确认兑换？"},
	SHOP_REFRESH={value="将花费%d钻石,确认刷新？"},
	DIAMOND_NOT_ENOUGH={value="钻石数量不足，是否进行充值？"}
}

return t_str
